/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSquadsIndexRouteImport } from './routes/_authenticated/squads.index'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players.index'
import { Route as AuthenticatedCompetitionsIndexRouteImport } from './routes/_authenticated/competitions.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSquadsIdRouteImport } from './routes/_authenticated/squads.$id'
import { Route as AuthenticatedPlayersIdRouteImport } from './routes/_authenticated/players.$id'
import { Route as AuthenticatedCompetitionsIdRouteImport } from './routes/_authenticated/competitions.$id'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin.packages'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminPackagesIdRouteImport } from './routes/_authenticated/admin.packages.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSquadsIndexRoute =
  AuthenticatedSquadsIndexRouteImport.update({
    id: '/squads/',
    path: '/squads/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompetitionsIndexRoute =
  AuthenticatedCompetitionsIndexRouteImport.update({
    id: '/competitions/',
    path: '/competitions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSquadsIdRoute = AuthenticatedSquadsIdRouteImport.update({
  id: '/squads/$id',
  path: '/squads/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayersIdRoute = AuthenticatedPlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompetitionsIdRoute =
  AuthenticatedCompetitionsIdRouteImport.update({
    id: '/competitions/$id',
    path: '/competitions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesIdRoute =
  AuthenticatedAdminPackagesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/browse': typeof AuthenticatedBrowseRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/squads/$id': typeof AuthenticatedSquadsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/competitions/': typeof AuthenticatedCompetitionsIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/squads/': typeof AuthenticatedSquadsIndexRoute
  '/admin/packages/$id': typeof AuthenticatedAdminPackagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/squads/$id': typeof AuthenticatedSquadsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/competitions': typeof AuthenticatedCompetitionsIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/squads': typeof AuthenticatedSquadsIndexRoute
  '/admin/packages/$id': typeof AuthenticatedAdminPackagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/_authenticated/competitions/$id': typeof AuthenticatedCompetitionsIdRoute
  '/_authenticated/players/$id': typeof AuthenticatedPlayersIdRoute
  '/_authenticated/squads/$id': typeof AuthenticatedSquadsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/competitions/': typeof AuthenticatedCompetitionsIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/squads/': typeof AuthenticatedSquadsIndexRoute
  '/_authenticated/admin/packages/$id': typeof AuthenticatedAdminPackagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/browse'
    | '/admin/catalog'
    | '/admin/packages'
    | '/competitions/$id'
    | '/players/$id'
    | '/squads/$id'
    | '/admin/'
    | '/competitions/'
    | '/players/'
    | '/squads/'
    | '/admin/packages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/browse'
    | '/admin/catalog'
    | '/admin/packages'
    | '/competitions/$id'
    | '/players/$id'
    | '/squads/$id'
    | '/admin'
    | '/competitions'
    | '/players'
    | '/squads'
    | '/admin/packages/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/browse'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/packages'
    | '/_authenticated/competitions/$id'
    | '/_authenticated/players/$id'
    | '/_authenticated/squads/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/competitions/'
    | '/_authenticated/players/'
    | '/_authenticated/squads/'
    | '/_authenticated/admin/packages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/squads/': {
      id: '/_authenticated/squads/'
      path: '/squads'
      fullPath: '/squads/'
      preLoaderRoute: typeof AuthenticatedSquadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/competitions/': {
      id: '/_authenticated/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof AuthenticatedCompetitionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/squads/$id': {
      id: '/_authenticated/squads/$id'
      path: '/squads/$id'
      fullPath: '/squads/$id'
      preLoaderRoute: typeof AuthenticatedSquadsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/$id': {
      id: '/_authenticated/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof AuthenticatedPlayersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/competitions/$id': {
      id: '/_authenticated/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof AuthenticatedCompetitionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages/$id': {
      id: '/_authenticated/admin/packages/$id'
      path: '/$id'
      fullPath: '/admin/packages/$id'
      preLoaderRoute: typeof AuthenticatedAdminPackagesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
  }
}

interface AuthenticatedAdminPackagesRouteChildren {
  AuthenticatedAdminPackagesIdRoute: typeof AuthenticatedAdminPackagesIdRoute
}

const AuthenticatedAdminPackagesRouteChildren: AuthenticatedAdminPackagesRouteChildren =
  {
    AuthenticatedAdminPackagesIdRoute: AuthenticatedAdminPackagesIdRoute,
  }

const AuthenticatedAdminPackagesRouteWithChildren =
  AuthenticatedAdminPackagesRoute._addFileChildren(
    AuthenticatedAdminPackagesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedCompetitionsIdRoute: typeof AuthenticatedCompetitionsIdRoute
  AuthenticatedPlayersIdRoute: typeof AuthenticatedPlayersIdRoute
  AuthenticatedSquadsIdRoute: typeof AuthenticatedSquadsIdRoute
  AuthenticatedCompetitionsIndexRoute: typeof AuthenticatedCompetitionsIndexRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
  AuthenticatedSquadsIndexRoute: typeof AuthenticatedSquadsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedCompetitionsIdRoute: AuthenticatedCompetitionsIdRoute,
  AuthenticatedPlayersIdRoute: AuthenticatedPlayersIdRoute,
  AuthenticatedSquadsIdRoute: AuthenticatedSquadsIdRoute,
  AuthenticatedCompetitionsIndexRoute: AuthenticatedCompetitionsIndexRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  AuthenticatedSquadsIndexRoute: AuthenticatedSquadsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
